using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Intensive.Data.SSDatabase;
using Intensive.Services.CTKAPIWrapper;
using Intensive.Services.Patching;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace Intensive.Services.Patching.TicketGenerator
{
    public class AutomaticPatchingTicket: PatchingTicket
    {
        public AutomaticPatchingTicket(ILogger<PatchingTicketGenerator> logger,
                                         SSDatabaseContext dbContext,
                                         CTKAPI coreCTKAPI
                                         ):base(logger, dbContext,coreCTKAPI)
        {
        }


        public override string GenerateTicket(COREAccount coreAccount, List<PatchingClient> clients, GeneratorConfig config)
        {
            string clientConfig = base.RenderPatchingClientConfiguration(clients);
            //log.LogDebug($"coreAccount: {JsonConvert.SerializeObject(coreAccount)}");
            //log.LogDebug($"clients    : {clients.Count}");
            //log.LogDebug($"config     : {JsonConvert.SerializeObject(config)}");

            string ticketText = MergeConfigWithTemplate(coreAccount, clientConfig, config);

            ticketText = ticketText.Replace("\r\n", "\\n");
            ticketText = ticketText.Replace("\n", "\\n");
            ticketText = ticketText.Replace("\t", "\\t");

            CORETicket tktData = CreateTicketData(coreAccount, ticketText);
            string ticketNumber = CreateCORETicket(tktData);
            
            return ticketNumber;
        }

        //returns the preview in text only form
        public override string GeneratePreview(COREAccount coreAccount, List<PatchingClient> clients, GeneratorConfig config)
        {
            string clientConfig = RenderPatchingClientConfiguration(clients);
            string ticketText = MergeConfigWithTemplate(coreAccount, clientConfig, config);
            CORETicket tktData = CreateTicketData(coreAccount, ticketText);
            string preview = CreateTicketPreview(tktData);

            return preview;
        }

        public override CORETicket CreateTicketData(COREAccount coreAccount, string ticketText)
        {
            CORETicket tkt = new CORETicket();

            //switch (coreAccount.SegmentName.ToLower())
            //{
            //    case "emerging":
            //    case "managed":
            //    case "rackspace cloud":
            //        tkt = new ManagedCORETicket();
            //        tkt.Status = (int)ManagedCORETicket.TicketStatus.ConfirmSolved;
            //        tkt.SubCategory = (int)ManagedCORETicket.TicketSubCategory.OSPatch;
            //        break;

            //    case "latam":
            //    case "enterprise services":
            //    case "corporate":
            //    case "intensive":
            //    case "managed colocation":
            //        tkt.QueueID = coreAccount.SupportQueueID;
            //        tkt.QueueName = coreAccount.SupportQueueName;
            //        tkt.Status = (int)EnterpriseCORETicket.TicketStatus.ConfirmSolved;
            //        tkt.SubCategory = (int)EnterpriseCORETicket.TicketSubcategory.WindowsPatching;
            //        break;

            //    case "ent z":
            //        tkt = new SegmentSupportCORETicket();
            //        tkt.Status = (int)SegmentSupportCORETicket.TicketStatus.ConfirmSolved;
            //        tkt.SubCategory = (int)SegmentSupportCORETicket.TicketSubCategory.Other;
            //        break;
            //}

            if (coreAccount.SegmentName.ToLower() == "ent z")
            {
                tkt = new SegmentSupportCORETicket();
                tkt.Status = (int)SegmentSupportCORETicket.TicketStatus.ConfirmSolved;
            }
            else
            {
                tkt = new EnterpriseCORETicket();
                tkt.Status = (int)EnterpriseCORETicket.TicketStatus.ConfirmSolved;
            }

            tkt.Subject = $"Proactive Patching - {DateTime.Now.ToString("MMMM yyyy")} (Automatic)";
            tkt.Account = coreAccount.Number;
            tkt.InitialMessage = ticketText;    //generated by parent class
            tkt.Recipients = coreAccount.CustomerContactIDs.ToArray();
            tkt.Requester = coreAccount.AM_ContactID;
            tkt.Severity = 1;
            tkt.SendMessageText = false;
            tkt.ComputerList = this.CoreDeviceList.ToArray();

            return tkt;

        }
    }
}
