<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AssemblyName>Intensive.Services.Patching</AssemblyName>
    <RootNamespace>Intensive.Services.Patching</RootNamespace>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>3.3.171</Version>
    <AssemblyVersion>3.3.171.0</AssemblyVersion>
    <FileVersion>3.3.171.0</FileVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <ShouldCreateLogs>True</ShouldCreateLogs>
    <AdvancedSettingsExpanded>False</AdvancedSettingsExpanded>
    <UpdateAssemblyVersion>False</UpdateAssemblyVersion>
    <UpdateAssemblyFileVersion>False</UpdateAssemblyFileVersion>
    <UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
    <UpdatePackageVersion>True</UpdatePackageVersion>
    <PackageVersionSettings>AssemblyVersion.IncrementWithAutoReset.None</PackageVersionSettings>
    <AssemblyInfoVersionType>SettingsVersion</AssemblyInfoVersionType>
    <InheritWinAppVersionFrom>None</InheritWinAppVersionFrom>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <ShouldCreateLogs>True</ShouldCreateLogs>
    <AdvancedSettingsExpanded>False</AdvancedSettingsExpanded>
    <UpdateAssemblyVersion>False</UpdateAssemblyVersion>
    <UpdateAssemblyFileVersion>False</UpdateAssemblyFileVersion>
    <UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
    <UpdatePackageVersion>True</UpdatePackageVersion>
    <PackageVersionSettings>AssemblyVersion.IncrementWithAutoReset.None</PackageVersionSettings>
    <AssemblyInfoVersionType>SettingsVersion</AssemblyInfoVersionType>
    <InheritWinAppVersionFrom>None</InheritWinAppVersionFrom>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="PatchingService.cs" />
    <Compile Remove="PullSettingsMetadata.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Intensive.Data\WSUS\WSUS.csproj" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\CTKAPIWrapper\CTKAPIWrapper.csproj" />
  </ItemGroup>

</Project>
