<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>3.3.171</Version>
    <AssemblyName>Intensive.Services.ActiveDirectory</AssemblyName>
    <AssemblyVersion>3.3.171.0</AssemblyVersion>
    <FileVersion>3.3.171.0</FileVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <ShouldCreateLogs>True</ShouldCreateLogs>
    <AdvancedSettingsExpanded>False</AdvancedSettingsExpanded>
    <UpdateAssemblyVersion>False</UpdateAssemblyVersion>
    <UpdateAssemblyFileVersion>False</UpdateAssemblyFileVersion>
    <UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
    <UpdatePackageVersion>True</UpdatePackageVersion>
    <PackageVersionSettings>AssemblyVersion.IncrementWithAutoReset.None</PackageVersionSettings>
    <AssemblyInfoVersionType>SettingsVersion</AssemblyInfoVersionType>
    <InheritWinAppVersionFrom>None</InheritWinAppVersionFrom>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <ShouldCreateLogs>True</ShouldCreateLogs>
    <AdvancedSettingsExpanded>False</AdvancedSettingsExpanded>
    <UpdateAssemblyVersion>False</UpdateAssemblyVersion>
    <UpdateAssemblyFileVersion>False</UpdateAssemblyFileVersion>
    <UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
    <UpdatePackageVersion>True</UpdatePackageVersion>
    <PackageVersionSettings>AssemblyVersion.IncrementWithAutoReset.None</PackageVersionSettings>
    <AssemblyInfoVersionType>SettingsVersion</AssemblyInfoVersionType>
    <InheritWinAppVersionFrom>None</InheritWinAppVersionFrom>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3"/>
    <PackageReference Include="System.DirectoryServices" Version="4.7.0"/>
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="4.7.0"/>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0"/>
    <PackageReference Include="Microsoft.Extensions.Options" Version="6.0.0"/>
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" ExcludeAssets="all"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CTKAPIWrapper\CTKAPIWrapper.csproj"/>
    <ProjectReference Include="../../Intensive.Data/ADMT/ADMT.csproj"/>
    <ProjectReference Include="../../Intensive.Data/SSDatabase/SSDatabase.csproj"/>
  </ItemGroup>

</Project>
