using System;
using System.Collections.Generic;

namespace Intensive.Data.EBIDataMart
{
    public partial class DimCompany
    {
        public int CompanyKey { get; set; }
        public decimal? CompanyBillingLatitude { get; set; }
        public decimal? CompanyBillingLongitude { get; set; }
        public string CompanyBillingGeoCodeAccuracy { get; set; }
        public decimal? CompanyShippingLatitude { get; set; }
        public decimal? CompanyShippingLongitude { get; set; }
        public string CompanyShippingGeoCodeAccuracy { get; set; }
        public string CompanyPhotoUrl { get; set; }
        public decimal? CompanyAnnualRevenue { get; set; }
        public int? CompanyNumberOfEmployees { get; set; }
        public string CompanyTickerSymbol { get; set; }
        public string CompanyJigsaw { get; set; }
        public string CompanyJigsawCompanyId { get; set; }
        public string CompanyConnectionReceivedId { get; set; }
        public string CompanyConnectionSentId { get; set; }
        public string OldRecordId { get; set; }
        public decimal? CompanyJsimpactsAddedFromDataCom { get; set; }
        public decimal? CompanyJsimpactsDataComManaged { get; set; }
        public string CompanyJsimpactsDataComMatched { get; set; }
        public string CompanyJsimpactsDataComDoesNot { get; set; }
        public string CompanyParentedStatus { get; set; }
        public string CompanyDataCleanHoldingAccount { get; set; }
        public decimal? CompanyReviewPriority { get; set; }
        public decimal? CompanyNumberOfP1Accounts { get; set; }
        public decimal? CompanyNumberOfP2Accounts { get; set; }
        public decimal? CompanyNumberOfP3Accounts { get; set; }
        public decimal? CompanyNumberOfP4Accounts { get; set; }
        public decimal? CompanyNumberOfP5Accounts { get; set; }
        public decimal? CompanyNumberOfCustomerAccounts { get; set; }
        public string CompanyEscalationNotes { get; set; }
        public decimal? CompanyNumberOfCloudAccounts { get; set; }
        public string CompanyReviewStatus { get; set; }
        public decimal? CompanyNumOfAccountsOwnedByInactive { get; set; }
        public DateTime? CompanyMatchedWithDataComOn { get; set; }
        public string CompanyEverEscalatedToRackspace { get; set; }
        public string CompanyAllAccountsOwnedByInactive { get; set; }
        public string CompanySupportOffice { get; set; }
        public string CompanyDataMigrationSegmentation { get; set; }
        public string CompanyDeleteRecord { get; set; }
        public string CompanyDataQualityDescription { get; set; }
        public decimal? CompanyDataQualityScore { get; set; }
        public string CompanyRkpi2DeletedFromRainking { get; set; }
        public decimal? CompanyRkpi2RkCompanyId { get; set; }
        public string CompanyRkpi2RkDefaultVisibility { get; set; }
        public string CompanyRkpi2RkRetrievalFlag { get; set; }
        public string CompanyLidLinkedinCompanyId { get; set; }
        public string CompanyApplicationsHosted { get; set; }
        public string CompanyBillingCounty { get; set; }
        public decimal? CompanyBudget { get; set; }
        public string CompanyCloudOnlyCustomer { get; set; }
        public string CompanyAccessSubmitter { get; set; }
        public string CompanyLogo { get; set; }
        public decimal? CompanyPriority { get; set; }
        public string CompanyRegistrationNumber { get; set; }
        public string CompanyComplianceRegulatoryObligation { get; set; }
        public string CompanyCountryNotSupported { get; set; }
        public string CompanyCreatedbyProfilename { get; set; }
        public string CompanyCrunchbase { get; set; }
        public decimal? CompanyCustomRevenue { get; set; }
        public string CompanyHipoTeamActivelyWorking { get; set; }
        public DateTime? CompanyHipoTeamAssignedDate { get; set; }
        public string CompanyHostingProvider { get; set; }
        public string CompanyLogoUrl { get; set; }
        public decimal? CompanyMrr { get; set; }
        public string CompanyOptOut { get; set; }
        public string CompanyOtherApplicationHosted { get; set; }
        public string CompanyRtbRecordId { get; set; }
        public string CompanyReferenceAccount { get; set; }
        public string CompanySearchInHoovers { get; set; }
        public decimal? CompanyClosedWonOpps { get; set; }
        public decimal? CompanyOpenOpps { get; set; }
        public DateTime EffectiveStartDate { get; set; }
        public DateTime EffectiveEndDate { get; set; }
        public int CurrentRecord { get; set; }
        public DateTime DwTimestamp { get; set; }
        public DateTime UpdatedDate { get; set; }
        public string CompanyId { get; set; }
        public string CompanyDeleted { get; set; }
        public string CompanyName { get; set; }
        public string CompanyType { get; set; }
        public string CompanyParentId { get; set; }
        public string CompanyBillingStreet { get; set; }
        public string CompanyBillingCity { get; set; }
        public string CompanyBillingState { get; set; }
        public string CompanyBillingPostalCode { get; set; }
        public string CompanyBillingCountry { get; set; }
        public string CompanyBillingStateCode { get; set; }
        public string CompanyBillingCountryCode { get; set; }
        public string CompanyBillingAddress { get; set; }
        public string CompanyShippingStreet { get; set; }
        public string CompanyShippingCity { get; set; }
        public string CompanyShippingState { get; set; }
        public string CompanyShippingPostalCode { get; set; }
        public string CompanyShippingCountry { get; set; }
        public string CompanyShippingStateCode { get; set; }
        public string CompanyShippingCountryCode { get; set; }
        public string CompanyShippingAddress { get; set; }
        public string CompanyShippingCounty { get; set; }
        public string CompanyTerritory { get; set; }
        public string CompanyPhone { get; set; }
        public string CompanyFax { get; set; }
        public string CompanyAccountNumber { get; set; }
        public string CompanyWebsite { get; set; }
        public string CompanySic { get; set; }
        public string CompanyIndustry { get; set; }
        public string CompanyOwnership { get; set; }
        public string CompanyDescription { get; set; }
        public string CompanyRating { get; set; }
        public string CompanySite { get; set; }
        public string CompanyCurrencyIsoCode { get; set; }
        public string RackspaceOwnerId { get; set; }
        public string RackspaceOwnerName { get; set; }
        public string CompanyCreatedById { get; set; }
        public DateTime? CompanyCreatedDatetimeUtc { get; set; }
        public DateTime? CompanyCreatedDatetimeCst { get; set; }
        public string CompanyCleanStatus { get; set; }
        public string CompanyAccountSource { get; set; }
        public string CompanyDunsNumber { get; set; }
        public string CompanyTradeStyle { get; set; }
        public string CompanyNaicCode { get; set; }
        public string CompanyNaicDescription { get; set; }
        public string CompanyYearStarted { get; set; }
        public string CompanySicDescription { get; set; }
        public string CompanyDandBId { get; set; }
        public decimal? CompanyNumberOfAccounts { get; set; }
        public decimal? CompanyFortuneRank { get; set; }
        public string CompanyLastReviewedBy { get; set; }
        public DateTime? CompanyLastReviewedOn { get; set; }
        public string CompanyIsRackspaceCustomer { get; set; }
        public string CompanyHighestLevelName { get; set; }
        public string CompanyMarketSector { get; set; }
        public string CompanyStatus { get; set; }
        public string CompanySubsidiaryLevel { get; set; }
        public string CompanyTaxIdVatNumber { get; set; }
        public DateTime? CompanyEffectiveStartDatetimeCst { get; set; }
        public DateTime? CompanyEffectiveEndDatetimeCst { get; set; }
        public DateTime? CompanyEffectiveStartDatetimeUtc { get; set; }
        public DateTime? CompanyEffectiveEndDatetimeUtc { get; set; }
        public string RecordCreatedBy { get; set; }
        public DateTime? RecordCreatedDatetime { get; set; }
        public string RecordUpdatedBy { get; set; }
        public DateTime? RecordUpdatedDatetime { get; set; }
    }
}
