using System;
using System.Collections.Generic;

namespace Intensive.Data.EBIDataMart
{
    public partial class TempVwNpsMot
    {
        public DateTime StartTimeFullDate { get; set; }
        public string StartTimeDayOfWeek { get; set; }
        public int StartTimeMonthNumber { get; set; }
        public string StartTimeMonthDesc { get; set; }
        public string StartTimeMonthAbbr { get; set; }
        public int StartTimeYearNumber { get; set; }
        public DateTime StartTimeHmsTime { get; set; }
        public int? StartTimeMilitaryHourNumber { get; set; }
        public int? StartTimeStandardHourNumber { get; set; }
        public int? StartTimeMinuteNumber { get; set; }
        public int? StartTimeSecondNumber { get; set; }
        public string StartTimeHmsStandard { get; set; }
        public string TeamName { get; set; }
        public string TeamDescription { get; set; }
        public string TeamReportHeader { get; set; }
        public int? TeamRoleId { get; set; }
        public string TeamBusinessSegment { get; set; }
        public string TeamBusinessSubSegment { get; set; }
        public int? TeamReportHeaderId { get; set; }
        public int? TeamBusinessSegmentReportId { get; set; }
        public int? TeamBusinessSubSegmentReportId { get; set; }
        public string AccountCaption { get; set; }
        public long? AccountId { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string AccountType { get; set; }
        public string AccountTypeDesc { get; set; }
        public string AccountStatus { get; set; }
        public string AccountSlaType { get; set; }
        public string AccountSlaTypeDesc { get; set; }
        public string AccountBusinessType { get; set; }
        public string AccountTeamName { get; set; }
        public string AccountManagerContactId { get; set; }
        public string AccountManager { get; set; }
        public long? AccountBdcContactId { get; set; }
        public string AccountBdc { get; set; }
        public string AccountPrimaryContactId { get; set; }
        public string AccountPrimaryContact { get; set; }
        public DateTime? AccountFirstServerOnline { get; set; }
        public int? AccountTenureDays { get; set; }
        public short? AccountBackupDeviceCount { get; set; }
        public short? AccountStorageDeviceCount { get; set; }
        public short? AccountOtherNetworkDeviceC { get; set; }
        public short? AccountServerCount { get; set; }
        public short? AccountUnknownDeviceCount { get; set; }
        public short? AccountAllDeviceCount { get; set; }
        public string AccountRegion { get; set; }
        public string AccountGeographicLocation { get; set; }
        public decimal? AccountSubscriptionAmount { get; set; }
        public byte? AccountEmerInstrExists { get; set; }
        public DateTime? AccountCreatedDate { get; set; }
        public string AccountBillingStreet { get; set; }
        public string AccountBillingCity { get; set; }
        public string AccountBillingState { get; set; }
        public string AccountBillingPostalCode { get; set; }
        public string AccountBillingCountry { get; set; }
        public string AccountShippingStreet { get; set; }
        public string AccountShippingCity { get; set; }
        public string AccountShippingState { get; set; }
        public string AccountShippingPostalCode { get; set; }
        public string AccountShippingCountry { get; set; }
        public string AccountPhone { get; set; }
        public string AccountFax { get; set; }
        public string AccountWebsite { get; set; }
        public string AccountCustomerType { get; set; }
        public decimal? AccountAnnualRevenue { get; set; }
        public int? AccountNumberOfEmployees { get; set; }
        public string AccountOwnership { get; set; }
        public string AccountTickerSymbol { get; set; }
        public string AccountDescription { get; set; }
        public string AccountRating { get; set; }
        public string AccountSite { get; set; }
        public string AccountCurrencyIsoCode { get; set; }
        public string AccountOwnerId { get; set; }
        public string AccountSourceSystemName { get; set; }
        public int ContactKey { get; set; }
        public string ContactNk { get; set; }
        public string ContactAccountId { get; set; }
        public string ContactLastName { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactSalutation { get; set; }
        public string ContactFullName { get; set; }
        public string ContactOtherStreet { get; set; }
        public string ContactOtherCity { get; set; }
        public string ContactOtherState { get; set; }
        public string ContactOtherPostalCode { get; set; }
        public string ContactOtherCountry { get; set; }
        public string ContactMailingStreet { get; set; }
        public string ContactMailingCity { get; set; }
        public string ContactMailingState { get; set; }
        public string ContactMailingPostalCode { get; set; }
        public string ContactMailingCountry { get; set; }
        public string ContactPhone { get; set; }
        public string ContactFax { get; set; }
        public string ContactMobilePhone { get; set; }
        public string ContactHomePhone { get; set; }
        public string ContactOtherPhone { get; set; }
        public string ContactAssistantPhone { get; set; }
        public string ContactReportsToId { get; set; }
        public string ContactEmail { get; set; }
        public string ContactTitle { get; set; }
        public string ContactDepartment { get; set; }
        public string ContactAssistantName { get; set; }
        public string ContactLeadSource { get; set; }
        public DateTime? ContactBirthdate { get; set; }
        public string ContactDescription { get; set; }
        public string ContactCurrencyIsoCode { get; set; }
        public string ContactOwnerId { get; set; }
        public string ContactHasOptedOutOfEmail { get; set; }
        public string ContactDoNotCall { get; set; }
        public DateTime? ContactEffectiveStartDatetime { get; set; }
        public string ContactCreatedById { get; set; }
        public DateTime? ContactEffectiveEndDatetime { get; set; }
        public string ContactLastModifiedBy { get; set; }
        public DateTime? ContactSystemModStamp { get; set; }
        public DateTime? ContactLastActivityDate { get; set; }
        public DateTime? ContactLastCuRequestDate { get; set; }
        public DateTime? ContactLastCuUpdateDate { get; set; }
        public string ContactDoNotMail { get; set; }
        public string ContactInactive { get; set; }
        public string ContactCoreContactId { get; set; }
        public string ContactContactTitle { get; set; }
        public string ContactDiscProfile { get; set; }
        public string ContactLanguagePreference { get; set; }
        public string ContactHobbies { get; set; }
        public string ContactSecretQuestion { get; set; }
        public string ContactSecretAnswer { get; set; }
        public string ContactEmail5 { get; set; }
        public string ContactEmail2 { get; set; }
        public string ContactEmail3 { get; set; }
        public string ContactEmail4 { get; set; }
        public string ContactPhone2 { get; set; }
        public string ContactPhone3 { get; set; }
        public string ContactPhone4 { get; set; }
        public string ContactPhone5 { get; set; }
        public string ContactSourceName { get; set; }
        public int? ContactCurrentRecord { get; set; }
        public int ContactDeletedDateKey { get; set; }
        public string ContactSso { get; set; }
        public string ContactType { get; set; }
        public string ContactSupervisorEmail { get; set; }
        public int? ContactPhoneExtension { get; set; }
        public string ContactEmployeeType { get; set; }
        public string ContactWorkShift { get; set; }
        public string ContactLocation { get; set; }
        public string ContactSupervisor { get; set; }
        public int? SurveyResponseIsComplete { get; set; }
        public int SurveyResponseLastPageNumberViewed { get; set; }
        public string SurveyName { get; set; }
        public string SurveyTitle { get; set; }
        public string SurveyDescription { get; set; }
        public string SurveyCreatedBySs { get; set; }
        public short? SurveyAllowEditCompleted { get; set; }
        public short? SurveyAllowResumeSurvey { get; set; }
        public int? SurveyMaxTotalResponses { get; set; }
        public int? SurveyMaxResponsesPerUser { get; set; }
        public short? SurveyIsActive { get; set; }
        public int SurveyQuestionPagePosition { get; set; }
        public int SurveyQuestionQuestionPosition { get; set; }
        public string SurveyQuestionQuestionAlias { get; set; }
        public string SurveyQuestionQuestionType { get; set; }
        public string SurveyQuestionQuestionCategory { get; set; }
        public string SurveyQuestionQuestionText { get; set; }
        public string SurveyQuestionQuestionSubText { get; set; }
        public string SurveyTypeName { get; set; }
        public string SurveyTypeDescription { get; set; }
        public string SurveyTypeSourceSystemName { get; set; }
        public int? SurveyNpsAnswer { get; set; }
        public string SurveyNpsRatingType { get; set; }
        public string SurveyFeedback { get; set; }
        public string IncidentReferenceNumber { get; set; }
        public string IncidentSubject { get; set; }
        public string IncidentCreatedMethod { get; set; }
        public DateTime IncidentEffectiveStartDatetime { get; set; }
        public DateTime IncidentEffectiveEndDatetime { get; set; }
        public DateTime IncidentRecordCreatedDatetime { get; set; }
        public string IncidentRecordCreatedBy { get; set; }
        public string IncidentRecordUpdatedBy { get; set; }
        public int IncidentSosFlag { get; set; }
        public string IncidentCreatorName { get; set; }
        public string IncidentSubmitterName { get; set; }
        public int IncidentEotr { get; set; }
        public string IncidentCategoryName { get; set; }
        public string IncidentCategoryDescription { get; set; }
        public string IncidentSubCategoryName { get; set; }
        public string IncidentSubCategoryDescription { get; set; }
        public int IncidentSubCategoryActive { get; set; }
        public string NpsSsk { get; set; }
        public string ContactRoleNk { get; set; }
        public string ContactRoleName { get; set; }
        public string ContactRoleDescription { get; set; }
        public int AccountServices { get; set; }
        public int AlertsAndMonitoring { get; set; }
        public int BreakFix { get; set; }
        public int ChangeToHardwareSoftwareOrNetworkConfig { get; set; }
        public int ChangeToHardwareSoftwareOrNetworkConfiguration { get; set; }
        public int CloudAndVirtualizationServices { get; set; }
        public int EmailServices { get; set; }
        public int EquipmentMaintenance { get; set; }
        public int ManagedBackupOrStorageServices { get; set; }
        public int NewGearOrNewServiceDeployment { get; set; }
        public int NewGearOrServicePurchased { get; set; }
        public int Other { get; set; }
    }
}
